#+YAML/TITLE: 证券系统的统一库存和账务模型
#+AUTHOR: Holbrook(wanghaikuo@gmail.com)
#+DATE: <2014-04-15 Tue>
#+YAML/LAYOUT: post
#+YAML/TAGS: 分析模式
#+OPTIONS: toc:t

库存和账务模型用于记录钱/物的流动。

被动账目系统与主动账目系统：嵌入处理规则，允许账目自行更新和管理



镜像托管与完全托管

* 账目

账目包含有价值的东西——钱或物。只能按照条目的方式进行增加和删除。
条目保存账目的所有变更历史——条目是账目变更的前提和依据。

有些业务领域，不仅要记录某个事物的当前值，还要记录该值每次变化的细节。这就需要账目。
比如，银行账目需要记录余额以及每次存、取款；库存记录需要记录当前库存以及每次出、入库情况。

我们可以用条目来记录账目的变化。



* 事务
事务把所有条目关联起来，以便审计。
条目不能被随意创建和销毁
在事务中，条目必须在账目之间移动

两种类型的事务：双腿事务，多腿事务


条目用来记录账目的变更情况。这些变更通常设计将钱/物从一个账目转移到另一个账目。
事务可以将两个条目关联起来，通过事务可以分析钱/物的来龙去脉——来自哪里，去向哪里。

一个基本的账务原理：需要核算的钱/物，永远不会凭空生成和消失，仅仅是从一个地方转移到另一个地方。

事务有利于保证账目的平衡——在业务周期上的各点，结算值都要归零。


多腿事务可以更加有弹性——在多个条目之间保持平衡，适合合并或拆分的场景。

* 汇总账目

把多个账目组合起来。可以进行成组的处理.

将账目区分为汇总账目和明细账目。

汇总账目不关联到条目，只是账目的集合（子账目可以为明细账目，也可以是汇总账目）。

汇总账目的条目，是所有子账目条目的集合。（子账目.条目)

当然，也可以不区分汇总账目和细目账目。即：作为集合的账目也可以关联到条目。

* 备注账目

如果需要生成一些不要求保持平衡的账目条目，可以使用备用账目。

备注账目是账目的另一个子类，通常用于备忘录。比如：记录要交税的账目。
备注账目不会发生事务！

（并不一定真的需要，严格来说，这不是一个“账目”，不满足约束条件）。预算？？？


* 记入规则

账目可以包含固定的规则，由这些规则来控制账目间的金额转移。

记入规则可以建立能互相更新并反映业务规则的动态账目网络。


有些条目根据另一个条目的自动生成，并具有一定的规则。

记入规则的技术方法要具备可逆性。即可以生成反向的条目。因为错误的条目不能删除，只能冲正。


记入规则可以使用“个体实例方法”、单个子类型、策略模式、内部case语句、解释程序和参数化方法等实现。

记入规则的触发方式可以是：
急切触发、基于账目的触发、基于记入规则的触发、向后链式触发等。


* 记入规则的执行模式

* 多账目记入规则


* 来龙去脉
最早，营业部交易

集中交易：对账务系统提出了更高的要求
+三方存管—— KBSS

新业务，。。。

最终：
