* 记笔记


*** 捕获——转发——存档

任何组织系统都有一个重要功能，就是能捕获新的灵感或者任务，并将相关的引用材料与之联系起来。Org 提供了一个捕获过程来创建任务。它将与一个任务相关的文件（附件
）保存在一个特定的目录下。在系统中，任务和项目经常移动。将整个项目树保存到一个归档文件中可以保持系统简洁快速。

**** 9.2 转送笔记

当你回顾捕获的数据时，可以想把其中的一些条目转送到另一列表中，比如说到一工程项目。剪切，查找正确的地址，然后再粘贴笔记，这就似乎有些麻烦。为了简化这个过程
，可以用专门的命令：

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 C-c C-w        转送光标处的条目或者区域。这个命令会提供一些目标地址供选择,你可以通过补全功能选择一个。条目（或者区域中的所有条目）就会作为一个子项填  
                充到目标标题下。                                                                                                                       
───────────────────────────────────────────────────────────────────────────
                默认情况下，当前缓冲区的一级标题会被作为转送的目标，你可以通过设置给出跨多个文件的复杂的定义。详见变量 org-refile-targets 的描述。     
───────────────────────────────────────────────────────────────────────────
 C-u C-c C-w    借助于转送功能的接口来跳转到一个标题。                                                                                                 
───────────────────────────────────────────────────────────────────────────
 C-u C-u C-c    跳转到 org-refile 最后转送子树所到的地方。                                                                                             
 C-w                                                                                                                                                   
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
**** 9.3 归档

当一个用（子）树表示的工程完成后，你可能想把它移走，不让它再在议程里显示。归档能使你的工作文件变得简洁，并能使议程视图构造等全局搜索保持高效。最常用的归档
命令是将工程树移到另一个文件——归档文件。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 C-c C-x C-a                   用变量 orgarchive-default-command 指定的命令归档当前的项。  
─────────────────────────────────────────────
 C-c C-x C-s 或者简化为 C-c $  将光标处的子树归档至 org-archive-location 指定的位置。      
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

默认的归档位置是当前文件同目录下，名为当前文件名后加 “_archive” 的文件。例子和设置位置的方法见变量 org-archivelocation 的帮助信息。下面是一个在缓冲区内设
置该变量的方法：

#+ARCHIVE: %s_done::

*** Org-mode写作的几个快捷方式
http://www.cnblogs.com/babe/archive/2012/04/11/2441633.html

*** 发布blog
这篇Blog就是在Org-mode下写成后直接发布到Wordpress中的(使用[[https://github.com/punchagan/org2blog][org2blog]])。

