#+TITLE: alpha策略的分类

alpha模型是量化交易模型的核心。通过对alpha策略的研究，才有可能获得与市场波动无关的回报。
本文根据alpha策略的内在属性，总结了alpha策略不同角度的分类方法。

* alpha策略

alpha回报是指扣除市场基准回报之后的投资回报，反映了投资者决策的价值。

* alpha策略的分类方法

** 按研究方法

  我们进行科学研究有两种主要的方法：理论推导（演绎法）和经验总结（归纳法）。

  理论推导方法在合理假设的基础上，提出用于解释事物的模型，对模型进行严格的数学推导，
  可以得出各种推论。如果经过实践检验没有证伪模型及其推论，则可以认为理论是正确的，
  并且基于理论可以对现实进行预测。

  经验总结方法认为对现实世界经过足够多的观察，也可以总结出规律。尽管没有严格的理论推导，
  但这些总结出来的经验依然可以预测现实。在进行归纳总结时，可以依靠统计学方法，使得从数据
  到结论的过程更加科学合理。而新兴的数据分析和挖掘、机器学习、深度学习等方法，可以极大
  降低对专业知识的要求，提高归纳总结的效率。

  对应到alpha策略，根据其研究方法也可以分为理论型和经验型。

  理论型的alpha从某种经济学理论对市场行为的解释出发，构建模型并用市场数据检验模型预测的
  准确性。根据市场理论的不同，理论型lapha模型
  大体可以分为趋势型(trend)，回复型(reversion),价值/收益型(value/yield)，
  成长型(growth)，品质型(quality)五种类型。

  行为金融学与价格行为学
 
*** 趋势型
    
趋势型策略也称为动量策略。其市场假设是：

#+BEGIN_QUOTE
趋势一旦形成，就会延续一段时间，直到形成新的趋势为止。如果能够识别出趋势并跟随，就能够获利。

  趋势一旦形成，就具有延续性。即走势会保持方向。
  当趋势衰竭时，趋势会终止，并形成新的趋势，新的趋势与原来的趋势必定不同。
  一般，将趋势定义为上升，下降，盘整 三种类型。

#+END_QUOTE

对于趋势策略的经济学解释，有“部分有效市场假说”，“博傻理论”等。

趋势型策略的关键在于对于趋势确立的判断。比如经典的“双均线”模型。

越早判断出趋势，获利的空间越大，但判断错误的风险也越大。所以，趋势型策略还要分析可能的风险和
可能的收益之间的比例，来决定是否进行操作。在操作开始之前，就要设置好止损的策略，避免过大的损失。

- 指标

### 趋势判断

1. 基于移动平均线
   传统的均线策略，认为短期均线上穿/下穿长期均线是趋势的确认点。

2. 突破型
   认为价格达到一个相对的新高/新低，表明形成了潜在趋势。比如：

3. 当前价格向上/向下突破某条均线



- 策略

  趋势类策略可能有趋势跟随或反趋势策略。

  趋势跟随策略在确认趋势形成后，与趋势同向操作。其问题在于：
  为了确认趋势的形成，趋势的开始阶段会被错过，无法在最高/最低价附近操作。
  如果提高灵敏度，必然会导致错误信号的增多。一般来说，不推荐过于灵敏的信号。 

  反趋势策略在趋势将要终结时，与现有趋势反向操作。其问题在于：
  理论上会亏损是无限的，所以必须设置保护性的止损。

*** 回复型
回复型策略的市场假设是：

#+BEGIN_QUOTE

价格围绕某个中心波动，如果能够识别出这个中心并判断出波动的幅度，就有可能从中获利。
一般来说，回复型策略是“逆趋势策略”，或称为“反转交易”。

#+END_QUOTE

根据波动中心或者波动幅度的不同定义，可以有不同的回复型策略，比如“均值回复策略”，
“超买/超卖(over-bought/over-sold)”策略，“背离策略”等。

最著名的回复策略如统计套利：两只相似的股票，其价格偏差会在一定浮动内来回波动。

- 均值回归

假设“价格序列”（如两个关联资产的价差）存在一个长期均值，价格对均值的短期偏离终将回归。

- 价格通道

假设价格会在一个通道（阻力线和支撑线之间）来回波动。阻力线和支撑线构成了通道的边界。
一旦价格到达通道的边界并跳回相反方向，应该立即新建长仓。如果价位到达阻力位应该新建短仓。
一旦价格到达相反的边界，就应该平仓。

问题：
对横向走势非常有用，但对上升走势和下降走势几乎没用。
在价格到达通道边界之前也可能发生逆转
一旦突破通道可能致使不可预测的损失。所以需要设置止损点。 

*** 价值/收益型

价值型策略研究某种基本面因素和股票价格之间的比率关系。并从比率失衡中寻找获利机会。

比如，市盈率(P/E,price-to-earning).

一般在模型处理上，以价格作为分母，作为某种收益率指标，这样便于分析的简单和一致。
比如，盈利收益率(earnings yield, = E/P), 股利收益率(dividend yield)等。
不难看出，收益率越高的股票，则其目前的价格相对来说越便宜。

市净率(book value to price), 息税折旧前收益(EBITDA)/企业价值(EV)

即使基于相同的收益率指标，也可以给出不同的策略。比如：

可以买入相对便宜的产品;

可以买入风险高的产品，卖出风险低的产品。（其理论认为，风险高的产品，其预期收益也会更高）;

携带交易(carry trade): 基于一个相对价差，买入价值相对低估的股票同时卖出价格相对高估的股票。



（1）价值投资策略，巴菲特即为典范，一般来说主要适用于传统产业。

*** 成长型

假设增长本身具有某种趋势性。增长快的资产，在一段时间内还会具有相对优势。
（2）成长性投资策略，菲利普•A•费舍为典范，特别适用于高新技术产业、中小企业板的公司分析。

*** 品质型
在其他条件相同的情况下，品质更好的金融产品更安全。

有很多指标可以用来标记品质，比如：
资产负债率，自由现金流等

*** 行为型

基于非有效市场理论。
BILL的《混沌操作法》中说道，市场存在一种看不见的根本结构。


（3）长期惯性投资策略。
（4）短期反转投资策略。
以上两个是基于行为金融理论的策略。


**** 反向投资策略CIS

**** 动量交易策略MTS

     市场能量的三个假设：

     1. 能量永远会遵循阻力最小的途径，所以阻力最小的途径即为价格的运动轨迹
     2. 存在着某种根本结构，这个结构决定阻力最小的途径。
     3. 这种始终存在而通常不可见的根本结构，不仅可以被发现，而且可以被改变。前提是要找到根本原因。

     策略：

     首先学习如何辨别主导交易行为的根本结构，然后根据你的交易宗旨改变或顺应这个结构。

**** 形态识别

- 早期的形态识别

- 市场分形

芒德勃罗用分形来刻画股票价格，显示了大的涨跌期模仿着每月、每天的价格波动，
于是整个市场从它的最大尺度到最小尺度是自相似的。
即，市场存在着分形结构的一致性。
在市场，结构存在于每一个趋势中：
结构存在于所有趋势（价格运动）的初期、中期和末期；
不同的趋势之间也存在着不同的结构，这些结构相互反馈，形成整体的价格波动。

发现一种根本模式,分形图集中98%的分形反映这种模式。市场分形涵盖着一种显著的行为变化。
所有的结构都包含变动与变动的倾向,
某些结构存在强烈的变动倾向,于是会出现突破和趋势行情.
较稳定的结构其成分会互相牵制以维持现状,于是有区间盘整行情.

用分形几何建立的市场测市系统应该能从分形结构的不同模式的特点,发出做多做空的位置和时机的信号.。
这种市场测市系统可以完整地分析任何走势图,
并在10秒钟之内便知道每一根K棒上应该采取的动作,买,卖,加码,停损,或离市.
达到”立即而正确地评估任何行情.
每天不需要花数小时分析行情,以至错失市场每天提供的许多机会…..
靠的就是对市场的根本结构和分形的自组织规律的透彻的了解.
通常的测度,
是不能对市场给出合适的描述的.
譬如传统的线性分析工具:波浪理论与各种定价模型；从其群体运动的基本特征，
转而又有人深入研究大众心理、实战心法、操盘铁则；技术指标、概率论、种种经济理论…..
也都试图找到某一突破口，从而发现股价运行的秘密。
在混沌理论体系中，上述种种，都仅只是一颗钻石的某一切面。
分形市场测市系统,不带有任何主观参数,规则和经验成分,
也不具有微分方程解的连续和缓的特征,
它反映的是市场价格自身运行的轨迹,
在各时间架构中,市场分形的形态特征表现的都是离散的时间间隔,
价格的变化在时,空二方面呈现离散的网络点和时间步.
因此,迄今市场上被广泛采用的各种技术指标,包括波浪理论的原理,工具,形态,结构,作用,功效等等,,
仅从几何特征和结构特征上看都不具有真正的分形的本质特征.
它们的形状大多是以光滑可导的曲线来表达,因而只是线性工具,而不是真正的分形.
在不同层面[时间架构]的剖析过程中,从分形结构模式变化中映射出来的方向,
在观察沿途各式各样情景的同时扑捉到市场的全部情况,关注过程而不是未来的目标或愿望,
确保所有的观察均基于“有理有据”的评估.
这不是一种经济性的,基本面的,技术面的,或智能化机械化的方法.
它不是根据过去的行为建立范本[template],并将其套用于未来,
也不是通过叠加一系列技术指标来判断市场走势.

选择合适的初始条件出发做交易能将交易系统的赢利能力大大提高，
以敏感的初始条件为基础进行交易,可以将赢利达到最大而风险最小!

分形混沌交易法的进场系统,
可以透露许多市场行为结构的演变讯息
当市场在高高低低之间波动时，我们可以藉由了解分形的行为而改善我们的交易绩效。
当分形形成时,不论它是在哪个市场品种,以及处在哪个时间标度[只要是用K线图表达市场的走势变化的]
总是具有相同的,简单的分形结构,不会任意变动的.需要识辩的是结构线及价格和它们之间的位置关系. 



*** 归纳型

归纳型策略采用数据挖掘技术，结合某种算法。比如灰色预测模型，神经网络，以及现在流行的机器学习和深度学习。

事实上，比较成功的模型，其行为类似与趋势型或回复型。


*** 反策略

反算法/反算法策略

探测别人/别的策略的止损、止赢点，或者市场规则（比如，强制平仓）。然后触发该条件。


** 按输入数据

   不管是理论型还是经验型alpha模型，都需要根据输入的数据预测市场行为。
   根据输入数据的不同，可以将alpha模型分为市场数据驱动和基本面数据驱动两类。

   比如，趋势型、回复型模型以市场数据作为输入；而价值/收益型、成长型和品质型模型
   以基本面数据作为输入。

- 需要的数据
  其中，趋势型和回复型需要价格数据作为数据；其他三种需要基本面数据作为输入。

** 按交易频率

超高频，高频，中频，低频

高频/超高频的alpha模型，关注价格的微观结构。



** 按投注结构

绝对，相对

** 按流动性

流动性好，流动性差

* 混合策略

* 常见策略

|   | 模型驱动 | 输入类型 |   |   |
|---+----------+----------+---+---|
|   |          |          |   |   |
|   |          |          |   |   |


- [(中长期)布林强盗系统](http://bbs.ihoms.com/bbs/cljs/5015.htm)
-  [(日内)横盘突破](http://bbs.ihoms.com/bbs/cljs/5007.htm)
- [简单均线策略](http://bbs.ihoms.com/bbs/cljs/5172.htm)
- [海龟策略](http://bbs.ihoms.com/bbs/cljs/5005.htm)
- [龟汤(反海龟之一)策略](http://bbs.ihoms.com/bbs/cljs/5111.htm)


* 其他

# 套利策略

基本上取决于数值分析。形式可以多种多样，比如
期限套利，ETF套利，跨期套利，跨市场套利，分级套利等


# 做市策略 

根据是否为指定的做市商，可以区分为主动和被动做市策略
# 其他

（8）波段策略。
（9）波浪理论及菲波那契、黄金分割策略。
（10）江恩系列技术策略。
请注意以上两个策略不能独立使用，一般用作辅助验证。
（11）浮动波长周期策略，该策略由波涛先生独立提出，具体内容尚未公开。
（14）跟庄型策略。
（15）易学策略，即中国传统的易学。
（16）神经网络策略。
（17）分形策略。
（18）遗传算法策略。以上三个为目前主要的三种非线性分析策略。
（19）停板策略。
（20）共振策略。
（21）筹码分布策略，等等。






# 参考资料
- 《海龟交易法则》，成体系的经典教案。
- 组合配比的部分，搞透Markowitz的理论，自己都可以建立适用的模型。
- [策略技术-恒生量化社区](http://bbs.ihoms.com/bbs/cljs/index.htm)


## 问题

理论上，这些策略都是可以使用的。大多数交易者也都在使用中，但结果仍然是90%的人亏损。探其原因。
关键在于如何让这些策略发挥正确的作用，也就是要让你的系统在适当的时机，发出正确的信号！譬如,
a，均线系统的滞后性，决定了它发出的信号必然滞后，按其信号操作，也必然不在合适的时机。。。。导致操作失败。
b，突破策略经常被无数的假突破（2B形态）干扰，使得你不断地反复止损，失去正常的心态，最终不可避免亏损告终。
c，逆势策略更是需要高超的技艺，把握不到恰到好处的时机，又不能适当的止损策略，很快就会爆仓的。
d，价格行为的模式识别，即常说的“形态”，要识别的形态之多，使人头大。
   同样的形态出现在价格的不同位置，其技术意义并不相同。
   更难的是，价格形态变化无常，往往价格多走一笔，W形态变成M形态。。。。如之奈何？
e，在通道里交易，问题在于，由于市场是非线性的，并非任何时间段，都可以划出合适的通道。
   通道交易者，必须随时跟踪价格变化，即时划出动态的通道线，这需要掌握合适的划通道线的技巧。。。。
f，还有数以千计的现役指标。。。。大多数存在同样的缺陷，因为它们。。。看出没有？
   正是这些策略本身的致命缺陷，导致绝大多数交易者失败的原因！。。。。
   市场是非线性的，线性思维、线性策略。。。当然不能对市场价格行为具备真正的适应性。
