#+TITLE: 从时效性视角看企业基础设施架构
#+AUTHOR: Holbrook(wanghaikuo@gmail.com)
#+DATE: <2012-04-14 Sat>
#+YAML/LAYOUT: post
#+YAML/TAGS: EA;CEP;ESB;SOA
#+OPTIONS: toc:t

业务视角，or 时效性视角？

* 业务角度的系统划分

传统上，银行将业务划分为前台、中台和后台业务：

1. 前台业务是一线的、面向客户的、直接盈利的业务。
2. 中台业务的职能是管理和控制前台业务。
3. 后台业务为前台、中台提供基础支持。

证券公司参考了银行的这种业务划分方法。在部门设置上，前台业务会根据业务类型成立相应的业务部门，
而中、后台业务部门集中设置，不区分业务类型。比如：

| 类别 | 业务     | 部门                                     |
|------+----------+------------------------------------------|
| 前台 | 经纪业务 | 理财服务部、运营管理部、营销服务部       |
|      | 投资咨询 | 研究所                                   |
|      | 承销保荐 | 承销保荐分公司                           |
|      | 证券自营 | 权益投资部、债券投资部                   |
|      | 资产管理 | 资产管理分公司                           |
|      | 其他业务 | 期货分公司、信用交易部                   |
| 中台 |          | 风险管理部、法律合规部、审计部、         |
| 后台 |          | IT部、存管结算部、HR、资金计划部、财务部 |


* 证券公司的应用系统

前中后台在目前流程银行中的是一个非常流行的概念

从所谓前中后台但是的历史渊源来说，对银行业来说是一个被衍生和借用的的新领域，必然和原先的概念理解是不同的

对于前中后台老胡了解到的理解有两个观点：

1）大部分的咨询公司角度理解的是:
直接面对客户，负责营销和服务的组织部门和人员为前台。
中台的理解是产品与服务研发、产品和服务的计价与组合，组合管理、集中作业等。
后台则是更为公共的一些企业职能，如财务管理、人力资源、资产管理、战略、合规、IT支持（也跨越前台和中台）等公共类职能。

2）还有一个观点是比较传统的，也比较扁平化的概念，即无中台的概念，除了面向终端客户的前台外，剩下的都是后台，也就是说没有中台。

其实从老胡的理解来说，这两种理解似乎都有些可以商榷之处，总体上我还是比较认同第一种观点，
但是第一种的所说的中台和后台其实也可以更为广义的上看认为就是传统概念中的后台，只不过今天的形式要求（例如集中化等）而重新总结的的产物。

前中后台总是这个高阶的三层没有异议的情况下，对于具体的职能归属不同的人也可能有不同的理解
其实柜台不一定是前台，因为柜台是客户找上门来，业务理解角度上看，柜台偏中后台。只有主动出击的零售银行部、公司银行部、金融市场部才是真正的前台。


从技术上来说：
前台就是展示与接收的平台；
中台是处理逻辑，分支流程的地方；
后台是结果存储，最终不变的集合。


常见的概念是理解后台最容易集中处理，以提高处理的效率，实际上中台的集中化处理今天已经是一个新的课题了，也确实存在部分方向上的集中化、虚拟化处理的可能
集中的作业处理，提高后台处理的效率，其实业界已经早在多年前已经有探索和成功案例，例如一些银行的集中录入中心、单证中心、集中审贷中心等。
未来的后台集中的方向上，老胡的理解是在集中授权中心、远程客户服务中心（部分已经实现）等等


这些个概念都是相对的，也有前台后置大集中的作法。


未来的后台集中的方向上，老胡的理解是在集中授权中心、远程客户服务中心（部分已经实现）等等


本帖最后由 ygjchina 于 2012-4-1 10:38 编辑

中台是个很虚拟的说法，三台业务的难点还是怎样建立依附在组织架构、业务流程上的业务分割方法。
从IT规划上看，中台集中处理各种业务逻辑，业务逻辑大部分与前台业务实时相关，所以从IT系统方面，落地时中台大部分功能是前台IT系统的组成部分。
从业务组织架构上看，中台建立业务集中处理中心，如单证中心，可以实现全行统一管理的目标，实践中，业务集中处理中心也是分散各地、分级管理的授权模式。

作者: starlight95    时间: 2012-4-1 17:58

银行系统前、中、后台的提法应该是伴随着综合前置而出现的。前台为柜面等展示和交易界面系统；中台接口发布，授权、复核等风险控制、收费，以及后来发展的业务集中处理（单证中心、审贷中心等），都归纳到中台；后台传统上是综合业务系统的账务系统，包含了部分非账务业务的数据库登记。

2005年前后流程改造兴起后，前台和中台得到了极大的丰富，基于SOA架构的瘦核心理念也逐渐得到大家的认可。前台更加突出了客户体验和营销概念，已具备了部分业务流程的管理功能；中台的风险管控能力得打加强，为了提高效率而生的业务集中处理中心也得到了加强；后台形成了已核心账务系统为中心的多个业务系统。至于FTP，ALM以及银行其他风险管控的系统、BI系统、OCRM等系统，作为银行业务系统的支撑系统存在。
作者: qzyang007    时间: 2012-4-5 15:01

传统上，证券公司业务部门分为

一般现在证券公司分前台，中台，后台，中台是客户服务，维护客户的，后台是和银行的柜台一样，做的是一般业务，前台，目前也是大多数券商招募的主要对象

各地营业部
经济业务部
研发部
自营部
资产管理部
投资银行部
并购业务部门
风控、稽核部
行政、财务、综合、办公室等


证券公司的内部分为三个体系：前台、中台、后台。前台主要是营销系列的。营销系列包括：普通客户经理、高级客户经理、区域经理、区域总监、营销总监等等。中台是指分析师团队，主要包括：首席分析师、助理分析师、投资顾问等等。后台系列主要是管理服务人员，职位包括：总经理、总经理助理、市场部经理、策划部经理（或职员）、招聘培训经理（或职员）、办公室（人力资源）、IT部门经理(或职员)、财务（会计和出纳）、风控经理（或职员）、前台接待（为客户开户）、客服部经理（或职员）、工作督导等等职务。另外不同的证券公司还会根据自己公司的实际情况设定不同的岗位。
希望对你有帮助，谢谢！



前中后台在目前流程银行中的是一个非常流行的概念

从所谓前中后台但是的历史渊源来说，对银行业来说是一个被衍生和借用的的新领域，必然和原先的概念理解是不同的

对于前中后台老胡了解到的理解有两个观点：
1）大部分的咨询公司角度理解的是直接面对客户，负责营销和服务的组织部门和人员为前台。中台的理解是产品与服务研发、产品和服务的计价与组合，组合管理、集中作业等。后台则是更为公共的一些企业职能，如财务管理、人力资源、资产管理、战略、合规、IT支持（也跨越前台和中台）等公共类职能。
2）还有一个观点是比较传统的，也比较扁平化的概念，即无中台的概念，除了面向终端客户的前台外，剩下的都是后台，也就是说没有中台。

其实从老胡的理解来说，这两种理解似乎都有些可以商榷之处，总体上我还是比较认同第一种观点，但是第一种的所说的中台和后台其实也可以更为广义的上看认为就是传统概念中的后台，只不过今天的形式要求（例如集中化等）而重新总结的的产物。



通常，我们从业务角度将证券公司的应用系统进行分类：

1. 前台
   - 经纪业务
     + 集中交易系统
     + 交易外围系统(交易客户端、Web交易、Mobile交易...)
     + 行情系统
     + 呼叫中心
     + CRM
   - 自营业务
   - 承销保荐
     + 项目管理系统
2. 中台
   + 风控系统
   + 合规系统
   + 审批系统
3. 后台

   + 三方存管系统
   + 估值系统
   + 清算系统

4. 业务无关
   + HR系统
   + 财务系统
   + 监管报送系统
   + OA
   + Mail



安装这种分类，规划处的企业基础设施架构可能是这样的：

- 数据中心
-
#+BEGIN_SRC dot :file assets/images/ea_of_securities_by_classify.png :exports results


#+END_SRC
