程序员的哲学修养
* others
介绍：参见阮一峰《禅与摩托车维修艺术》读后感
http://www.ruanyifeng.com/blog/2011/12/zen_and_the_art_of_motorcycle_maintenance.html
《The Tao of Programming》
《 The Zen of Python》

* 禅
于 12-4-4 通过 爱范儿 · Beats of Bits 作者：陶 醉



受日本文化影响，禅作为一种处世的哲思，已经被西方社会所普遍接受，如今各行各业都有人在愉快地讨论其业内的禅意。有《 The Zen of Gambling 》，即赌博的禅；也有《 The Zen of Tennis 》，网球的禅；还有《 The Zen of Beef Ribs 》，即烤肉的禅；更无语的有《 Christian Zen 》，即基督的禅。这些书里，禅也就是整体把握或洞察力的意思，但带上禅字之后，整本书一下就时髦了不少。而《 The Zen of Zombie 》，僵尸的禅；或《 The Zen of Oz 》，绿野仙踪的禅；《 The Zen of Cat 》，猫的禅等，内容虽离奇，但其实更富禅味。

禅文化影响广泛地让人讶异。在基督教文化背景下，禅文化能得到广泛的接受，不得不归结于禅本身神学气息的淡薄；同时也说明日本世俗文化的广泛影响力。毕竟，能像高明的日本武士那样，凭着直觉，快刀斩乱麻地解决问题，是所有人的期盼。

对计算机行业来说，因为其技艺崇拜情结以及 Geek 文化，禅的影响更加深刻。至少《 The Zen of Assembly 》、《 The Zen of CSS Design 》、《 The Zen of Programming 》、《 Zen of Palm 》、《 Zen of Code Optimization 》等书名就很“禅”。事实上，就没有哪门程序设计语言或哪个软硬件分类没有出过一本用禅做书名的书。


Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.

以上是摘自》的头四句子，这四句很好的说明了为何计算机从业者尤其是程序员们，特别喜欢禅的意境。美的优于丑的，显式的优于隐式的，简单的优于复合的，复合的优于复杂的。禅在艺术上的表现，不正是如此么？

程序开发、硬件设计，都要求反复地从庞杂的元件体系中抽象出整体的认识，再以最小的代价去修改原有的体系以实现这种认识。整个过程都只在脑海中进行，敲下代码之前，已要了然于心。当这种能力达到极致的时候，物我不分，也差不多就是证悟的境界了。程序员们，尤其是 Geek 们对禅的追求，不仅仅是叶公好龙，或者是方法论上的。反映在日常的生活上，就是程序员们普遍对禅的艺术抱有极大的兴趣。

而有些计算机人走的就更远，他们为了探究自我的终极境界，选择直接修习禅宗本身。

其中就有乔布斯。



世人皆知乔布斯的宗教信仰是禅宗，但或许是西方社会之人对佛教繁杂的体系望而却步的原因，很少有书籍能深入地进行讨论。不过即使不深入，热点也是不能放过的，也就有那么一本叫做《 The Zen of Steve Jobs 》的漫画书，最近刚新鲜上市。书名里用的虽是 of 这个单词，但编的却是乔布斯的禅修及他与一个禅匠间的友谊，而不是写乔布斯表现出什么禅意。要翻译的话，我建议取名叫做《乔布斯与禅宗》。

有句话说的好，认真你就输了。但哪怕作者开章明义说是编的，哪怕他的读者事实上也不关心禅宗到底是怎么回事，哪怕读者们甚至也不关心乔布斯究竟如何修行，只不过好奇名人的传奇故事罢了。但我还是想说，这本漫画编的非常有问题。

这问题是，乔布斯拜的是个曹洞宗的师父。



佛教各门各部已然够多的了，禅门里又还有五宗七派之说，曹洞宗是目前较显赫的一宗。不过虽然修行者甚众，曹洞宗历来给人以“土”的感觉，在日本初传时，更被称为是“农民禅”，很重要的原因是其修行相当朴素。漫画里那些禅机对话、以箭法证道什么的，完全是先入之见，看过一笑就好了。

如果是为了追求智慧、美学、甚至是顿悟来学习禅宗的话，入曹洞宗门下修行，那真是南辕北辙了。曹洞宗的和尚虽然也能谈禅机公案，也能吟诗作画、射箭摆茶，但他主业就是坐着，坐禅。就是所谓“日面佛，月面佛”的默照禅。弟子们来到禅堂或美国那个什么中心的话，不会做任何其他事情，只能是打坐。当然，如果照现实描写的话，画漫画只能出一页就完了。

那坐禅时是在冥想吗？也不是，坐禅正是为了不想。坐禅是为了顿悟吗？也不是，这事儿强求不得。那坐禅有什么用呢？其实也没有什么大用，见性成佛，这只是修行的其中一种方法，绝对不保证有效果。与其他宗派相比，曹洞宗只不过是认为这样更管用一些，就一直这么做了。

如此不靠谱，学来何用？就拿乔布斯来说，按照实际发生的情况来看，在八五年被逐出苹果之后，乔布斯确实跟随曹洞宗传人乙川弘文修行了一段时间，过从甚密，以至于其婚礼都是乙川弘文主持的。但九十年代后，乔布斯就与乙川弘文几乎断绝了往来，直到两人先后去世。这难道不正好说明曹洞宗完全没什么用，以至于乔布斯兴头过后就抛到一边去了？

曹洞禅是祖师禅，不立文字，不依言语，直接由师父传给弟子，祖祖相传，心心相印，见性成佛。但师父对徒弟有用，只是因为一开始修行会有困难、没经验，需要有人指导。师父的作用也只是将初学者带入门而已，是自我的镜像，当明白自我之后，也就不需要有师父。至于私交就更不影响修行，不相往来，不说明什么问题。

乔布斯心里怎么想的，没人会知道。不过，参禅虽说务要出世，但目的还是有的，而且非常明确。曹洞宗的高僧宠智正觉就说过，“参禅一段事，其实要脱生死，脱生死不得，唤什么作禅？”，曹洞禅坐禅的目的正是为了在默坐的过程中，放弃一切思考，感受到无我的境界，也就是明空了、知死生。

当有人患了癌症之类的恶疾，得知自己只有两三年可活时，往往会寻找一些精神上的支持。有人会选择依赖上帝的帮助，有人也许会开始坐禅。如果是选择坐禅，那么他修行的目的将会是体悟心的空性。这意味着，他努力想要从二元思维带来的痛苦中超脱出来，这就是修习“色不异空，空不异色”。这样的修行当然会对他有所帮助，但那还不算是完满的修行。

知道生命短暂，所以尽情去品味每一天、每一刻，这就是“色即是空，空即是色”的人生。佛来的时候你会欢迎他，魔来的时候你也一样会欢迎他。中国著名的马祖道一禅师说过一句名言：“日面佛，月面佛。”有一次，他生了病，有人去看他时，问他：“你还好吗？”马祖禅师回答说：“日面佛，月面佛。”这就是“色即是空，空即是色”的人生。这是不会有烦恼的人生。有一百年可活固然美好，但只有一年可活也同样美好。只要你持之以恒地修行，就一定能达到这个境界。

修行之初，你会碰到各式各样的困难，这时你有必要做一些努力来让修行贯彻下去。对初学者而言，不需要努力的修行并非真正的修行，因为初学者的修行是需要花大力气的。尤其是对年轻人来说，必须非常刻苦耐劳才能略有所成，你必须竭尽全力。色即是色。你应该忠于自己的感觉，知道你完全忘掉你自己为止。

在达到这个阶段之前，要是你以为你做的一切都是禅或者以为修不修行都无妨，那真是大错特错。相反的，如果你倾全力去修行而又不带有得失心，那么你做的一切就是真正的修行。做任何事情时，都应该以“把事情做好”当作唯一目的。如此一来，色就会是色，而你就会是你，真正的空性也将会体现在你的修行之中。

《品味生命中的每一份、每一秒》段《色即是空，空即是色》章

《禅者的初心》 铃木俊隆著

众所周知，影响乔布斯最大的书算得上是《禅者的初心》了，而作者铃木俊隆是著名的到美国弘法的禅师，也是乙川弘文的师父，真正是乔布斯的师祖。我之所以摘这么长一段铃木俊隆的说教，是因为这段话根本就是乔布斯在确诊癌症之后实际躬行的写照，连一个字也不用改动。如果一本书，对一个人影响到了这样的程度，那也只能用“圣经”二字来形容了。

有人会说，不，乔布斯真正信的是完美主义，而且待人也极不随和，还讳疾忌医、大搞饮食疗法什么的，哪像个平和的佛教徒？

“完美”二字，世上其实是不存在的。逼迫自身以致驱使他人去追求完美的境界，也就是去追求物我合一，要物来反应我、我也要尽力能表现物的终极目标。这是个永不停歇的自证的过程，坐禅修行能巩固自己的信念，抛弃自我来追求这样的终极目标到底。这正是很多人选择参禅的原因，日本武士们即是例子。

至于待人随和，品相清净什么的，事实上，禅宗算得上是大乘佛教里的小乘，修成了也不过是个“自了汉”，如果不出家继续度人的话，那很可能不会有人所共知的那种吃斋念佛的佛教徒的修为。

而修禅之人还讳疾忌医、胡乱吃药这种事情，其实所在多有。其根源在于，禅宗在神学上并不深入。

禅宗理论只到佛教基本的四圣谛、五蕴、八正道、十二因缘、二无我为止，其他大部头经藏都只学而不修。因此其在神学意义上是不排他的，修行之人还要相信些其他什么的，甚至寄托于巫医外道，那也只能是悉听尊便。雍正皇帝习禅非常认真，却吃道教铅丹乃至中毒，可为一例。

有个公案说的很明白，悟道之前，砍柴挑水，悟道之后，砍柴挑水，外人看去，丝毫无变化。能看出一个人习禅是否有所得的，恐怕只能是他对待生死的态度了。而就乔布斯而言，也许还可以再加上一些手机、平板电脑等身外之物。

当然，我也无法证明乔布斯习禅与乔布斯构想出 iPhone 间有因果关系，因为习禅本身就是为了跳出因果。我只能说，乔布斯习禅是实在的，因为他生命的最后一段时间算的上是暴露在媒体之下。明知自己只剩下几个月的日子，依然如常的发布产品、召开会议、关心项目，对待亲友也如日常，直到完全倒下。凡此种种，如果没有悟出点什么，是绝对做不到的。

有人说我不用参禅也能悟得此平常心的境界，那恭喜你省了修行了。佛性本来人人皆有，其实也无奇特之处。

举乔布斯为例，是为了说明禅宗，尤其是曹洞宗究竟是什么。另外，乔布斯可说是西方社会里特立独行的人物，而世人又纷纷要效仿他的成功。那么除了学他穿牛仔裤，说 one more thing 之外，探究此人真正追求过什么，怎么追求的，追求的东西有无意义，不是更加重要？

很多人喜欢禅，只是喜欢禅的艺术表达，特别是带日本文化风格的禅的艺术。然而，倘若硬要临摹这种风格，照猫画虎，很可能反而还类犬。禅的根在中国，如今禅宗在西方开枝散叶并结出硕果，不少中国人却当此为日本所创；略懂一二的，也持西方主流文化的观点，视禅为非主流的儿戏，岂不悲哉。

禅宗这个佛教宗派，与实践“禅那”及瑜伽的如来禅是两码事，但其实又不如胡适所说的那样，是完全的革命，禅宗之人也研习佛经，也通晓法事，这不是区别。而禅宗里各派别又有不同，如曹洞宗就默默坐禅，另还有喝骂弟子，甚至实施棍棒教育的，《五灯会元》等书里，写的相当精彩。

如果硬要加以定义，只能说禅宗是中国文人的佛教，反映出士大夫阶层对精神寄托的需要。



禅宗的兴衰直接反映着中国文人的心理状况。中国文化自信的时候，禅宗就兴；文化黯淡的时候，禅宗就衰。唐时禅也清新，南宋时禅也寂寥，明末多狂禅，清时已无禅，大地茫茫只剩一片净土。

至于如今。

如今就拿曹洞宗来说，曹洞宗所谓正统所在，就是江湖上如雷贯耳的河南嵩山少林寺了，恐怕大家对其拳脚功夫还更熟悉些。修行上，也是禅宗、净土宗合一。念阿弥陀佛，尊《净土三经》的，早已经不是原来的禅宗。而坐禅一事，在少林寺 CEO ，不，方丈释永信大师与名媛杨澜小姐谈起时，也只认为是“基本功”了。当然，在选功夫之星时，这基本功夫还是必须看重的。

那么，不重拳脚功夫，禅宗在中国兴盛时，重的是什么呢？

春有百花秋有月，夏有凉风冬有雪。若无闲事挂心头，便是人间好时节。（赵州从谂）

人闲桂花落，夜静春山空。月出惊山鸟， 时鸣春涧中。（王维）

庐山烟雨浙江潮，未到千般恨不消。到得还来别无事，庐山烟雨浙江潮。（苏轼）

以上三首，都是借物以抒发禅意的诗。禅宗的特点在于其内在的理性化，几乎没有神学气息，而外在又要求是诗性化的，自然就受到文人士子的高度推崇。如大诗人王维，就以学佛参禅知名，被称为“诗佛”。反过来说，历代名僧，如贯休、贾岛、仲休等都可以说是披着僧衣的文人。文人与僧侣间相互唱和、谈禅，写下了大量不朽的诗歌。禅宗所重，其实是诗。

菩提本无树，明镜亦非台，本来无一物，何处惹尘埃。

既非风动，亦非幡动，仁者心动耳。

六祖慧能，虽说是不识字的火头僧，但上面两偈之所以让他人也能体会到其已顿悟，根本原因在于语句中体现的诗性。至于六祖后的历代高僧，要是不作出首把拿得出首的禅诗，简直就不好意思说自己顿悟了。以下二首开悟诗，不明就里的，还真以为是什么青年才俊为讨好佳人时所写。

金鸭香销锦绣帏，笙歌丛里醉扶归。少年一段风流事，只许佳人独自知。（昭觉克勤）

岩上桃花开，花从何处来？灵云婵一见，回首舞三台。（觉海法因）

说起来这也是很矛盾的事情，禅宗讲究不立文字，要的是直觉感悟，但人与人沟通毕竟要有媒介，求助于诗文只能说是少数可被接受的方法了。禅以诗为证，可以称的上是诗之禅吧。

文化酸腐之时，写诗论文很容易就流于形式，变成狂解。曹洞宗正是对这种形式主义的反动，即又号召大家回到默坐的修习状态。曹洞宗、临济宗等禅宗门派，带有孤寂的含义，同时又能锻炼内心，且不过于复杂，一传入日本，就大受这个岛国民族的欢迎。

宋室飘零，文人寂寥。南宋后禅宗东渡日本，在寂寥上更添加了一点点贫困（语出《禅与日本文化》，铃木大拙著）的特质，这是日本民族性格的反映，禅的体用无大变化，等于是将南宋时中国文人的一部分精神面貌保留了下来。

武士阶层或一般民众，少习文字，能作一两句俳句就已经是相当风雅的事情。但曹洞宗等修的也还是禅，其禅意也是要发挥出来的，否则既无法自证，也无法传播。于是僧俗们就多诉诸于自身的手艺，抒发禅意在日本简直变成整个民族的文化行为了。花道、茶道、剑道、武士道，各种技艺的高度诗性，无不是对禅意的一种领悟和发挥。此所谓艺之禅。



在计算机主导的时代，禅文化又再次涅槃，渗透到了更加理性的领域。 WordPress 项目里有句口号叫做 Code is Poetry ，代码即诗，也许诗性从来就是理性所不可缺少的另一半。计算机行业算来应该是工匠之属，姑且称之为匠之禅吧。

匠之禅与艺之禅都大行于世，原本的诗之禅何时可能复兴？

《断章》是一系列对物件和片段的思考，我们用它描绘科技与人文的犬牙交错。

《断章》一 · 马赛克 <http://www.ifanr.com/78050>
《断章》二 · 字 <http://www.ifanr.com/79939>
《断章》三 · 禅 <http://www.ifanr.com/80965>
