#+TITLE: 简历
#+DATE: 2015-01-27
#+AUTHOR: 王海阔
#+EMAIL: wanghaikuo@gmail.com

* 个人简介

王海阔(Holbrook Wong)，男，生于1977年5月。2000年毕业于清华大学化工系。

经历过互联网创业，做过3年的项目经理，2年售前顾问，后专注于企业架构(EA)、企业级和互联网基础设施，以及基于开源产品的解决方案。
熟悉软件过程和方法，以及相关的开源工具。
作为兴趣，关注较新的互联网开发技术，并会尝试开发一些小型的应用。

个人技术博客: http://holbrook.github.io/

* 过往业绩


+ 在宏源证券信息技术部研发岗位工作4年，主要业绩包括：

  参考互联网行业的技术和解决方案，基于开源的LVS、Nginx、Keepalived搭建企业级的高并发、高可用互联网接入平台，
  实现双链路接入和应用系统的负载均衡支持。支持统一的https/http协议转换、SSL证书管理，域名和虚拟目录的整合。
  平台可以替代F5等硬件负载均衡设备，并提供更多的功能和更大的灵活性。

  进行SOA架构体系设计和实施，用开源的Mule、FUSE等ESB产品实施办公、管理类系统的整合，并通过KCXP(金证）、T2(恒生）、FIX（顶点）等协议，
  实现与交易类、营销类系统的对接；
  负责交易结算类业务系统的ESB(使用恒生的统一接入平台)的项目实施和管理以及技术研究和扩展工作。

  制定配置管理、问题管理、版本管理、发布管理等软件过程管理的规范并指导实施，搭建svn和git(版本管理）、jira和redmine（缺陷/问题管理)、
  Hudson(持续集成)等工具，并进行相关的软件过程方法的培训和推广使用。

  提供linux、oracle、Robot Framework、LoadRunner等软件和工具，以及性能测试、分析和优化等工作的技术支持。

  支持运维相关的技术研究工作，基于vmware、OpenFiler搭建虚拟化的实验环境，使用开源的salt实现大量服务器的批量化安装配置管理，
  基于salt开发了恒生统一接入平台(T2)的配置管理工具，搭建yum源、统一备份服务器等运维基础设施；使用Ganglia实现集群监控。

  研究规则引擎和CEP、ZeroMQ和RabbitMQ、OSGi、MooseFS和DRBD（分布式存储）等技术，作为储备。

  负责开发商实施的统一接入系统（顶点）、债券自营系统(衡泰）、中债直联系统（衡泰）、等系统的甲方项目管理和协调工作。

+ 在环亚时代（已被华胜天成收购）工作5年

  前两年担任售前顾问，负责了解客户需求、提出解决方案、针对方案的讲解和沟通，以及项目报价工作，
  后期支持研发中心，研究Flex、WPF等前端展现技术，并在监控管理产品中应用。

+ 在中软国际3年时间，担任项目经理，主要负责区域政府型客户的软件项目实施。

* 工作经历

- 2010年10月至今，宏源证券，信息中心-研发部
- 2005年6月–2010年9月，环亚时代，解决方案销售部/研发中心
- 2002年4月–2005年4月，中软国际，行业应用一部(电子政务事业部）
- 1999年6月–2001年12月，互联网创业

* 教育背景

- 2007年9月–2009年9月，外交学院，世界经济专业，在职研究生结业
- 1995年9月–2000年7月，清华大学，化学工程与工艺专业，或工学学士学位
- 1992年9月–1995年7月，黑龙江省牡丹江农垦高中
